---
title: "Celigo_Data_Import"
output: html_document
date: "2026-03-19"
---

```{r load-libraries}
library(tidyverse)
library(rstudioapi)
library(dplyr)
library(data.table)
```

```{r Well-Level-Import}
# === DATA IMPORT ===
runs_included = 1

read_multiple_files <- function(n_files = runs_included) {
  data_list <- list()

  for(i in 1:n_files) {
    cat("Selecting file", i, "of", n_files, "\n")

    user_input <- showPrompt(title = "Organizing Data:", message = "Enter dataset name. Next select the corresponding tabular .csv and condition .csv")
    
    file_path <- file.choose()
    data <- read.csv(file_path, skip = 15, header = TRUE, check.names = TRUE) %>%
      dplyr::select(1:39) %>%
      filter((Row %in% LETTERS[1:8]) & (Column %in% 1:12))
    
    condition_path <- file.choose()
    Condition <- read.csv(condition_path, check.names = FALSE)
    data <- data %>%
      left_join(Condition %>% select(Well, Condition), by = "Well")
    
    data$Source <- user_input
    data_list[[i]] <- data
    
    cat("Combining", file_path, "and", condition_path, "\n")
    cat("Added dataset:", user_input, "\n\n")
  }

  combined_data <- do.call(rbind, data_list)
  return(combined_data)
}

NET_Data_Combined <- read_multiple_files(runs_included)

NET_Data_Combined <- mutate(NET_Data_Combined, across(starts_with("X.."), ~as.numeric(gsub("%", "", .x)) / 100))
NET_Data_Combined$Condition <- gsub("\\\\n", "\n", NET_Data_Combined$Condition)
names(NET_Data_Combined) <- gsub("^X\\.\\.", "%", names(NET_Data_Combined))

NET_Data_Combined$MPO.Index <- as.numeric(NET_Data_Combined$'%MPO') * as.numeric(NET_Data_Combined$'AVG.MPO.Mean.Intensity')
NET_Data_Combined$CitH3.Index <- as.numeric(NET_Data_Combined$'%CitH3') * as.numeric(NET_Data_Combined$'AVG.CitH3.Mean.Intensity')
NET_Data_Combined$DAPI.Index <- as.numeric(NET_Data_Combined$'%DAPI') * as.numeric(NET_Data_Combined$'AVG.DAPI.Mean.Intensity')

setDT(NET_Data_Combined)
```
